import {
	GETHISTORY_AJAX,
	GETHISTORYTREE_AJAX,
	EDITHISTORY_AJAX,
	EDITHISTORYTREE_AJAX,
} from './request';
/*import {
	GETHISTORY_AJAX,
	GETHISTORYTREE_AJAX,
	EDITHISTORY_AJAX,
	EDITHISTORYTREE_AJAX,
} from './requestLocal';*/
export {
	GETHISTORY_AJAX,
	GETHISTORYTREE_AJAX,
	EDITHISTORY_AJAX,
	EDITHISTORYTREE_AJAX,
}